sudo: required
language: bash
services:
- docker
before_install:
- docker pull archlinux/base:latest
- docker build -t jinwuzhao/emacs .
deploy:
  provider: script
  script: bash docker_push
  on:
    tags: true
env:
  global:
  - secure: BcWgdmCeUSmRwyFTv73FQOFEfuCPGVy+r5vaZ94EytpDTjWIF1GGOi7/N9KyBzM7WRqd91g5te+1OW7f+cXmuWds1DKFJcBqh1Y9gRTNgU3VcST3QHkoqnGRvM+UcwbPQIaKXY4PAIAVxAqrVl/AWXAya33I8P3DsKcL/GdBkMmzBLLcHaaOhBIwcFzcQdrPKpXJj/VzQYZvyWWfhbdaVQmSpuYoG8ilcs6BSGSzVpsdqdHprDMhNCq88sdDSOMDQn6gwqIClEAqk6pp3HCtQfLTB2yDtHC4CrJsl8p+fH31TjAkriADTAkKyzbRLg2mpXAnBRFQDfuBxuj53JiyujZKr2HRlaMuaeKU+lDb8fkDNEzO6Fnrksp6E/XzQa+h5IzOSkyntT5KymLDFQqvq1IkR+ytkGAL2FIe66SKctdDQG3SUdTfXi/Ox1VVQ2Eyw3spAoWdcWd1ZdKwWAfh8PXDHW8P+Htpx+ImpMxKcxrNbjI/btJPm1KvkopMq6+wUD/mU2vMh7ANV+byG85TC2RehtPhUvTENtSciiGe+wCzL/sQZOKtf/d8UUV0igBRbsedBvC6xvMNnjzgxNNNuIgHDYkz6Mts3bxe1XM3yjda5WPzKfw2bU4gI/NYtU6jdUrnUUvR0zMQVC5rx/t7PH7Ff/GYi4EJkeNxm0Hcbl4=
  - secure: XChyWePi6RtxCoBJQr77i4fAhrP0gfkT3cdwM+Jh/XFrvVxXZmQQE1kt6/rUwAILO6EdGnB98GT4g9+C0yU5VQa8Gv3iA4V9YC94bIm3ZOsiAHRVKJTR5l4EsdHmw5l0fqGfIt7PKq9yxIsJXFzcBUnqeJ8CNNyHm4wIVTotauUnIo7q4v0I9gRZv9vLxG8CxrDe9VXPLKlpsVjNABsmQa5ha0EPR/cmFsbC5+11u3B9soA78q3jfRRSjM1hh/a96PVsisXiX4gE/+uZzmKuHbYreC7lpCmnR+PC23d3TZ4SSB5vTscRGwoJkNvAxroqHSMWcsBjBhmmG5x0tRgjrDTgC9fuloyBZBLGC8I2+na/plF4n2jSJivJYaPOLGNUnFIU2QXr8rG6mmIQIVhYNmXxKpJEHh3LMpl9HJkL578iolW+Gn2+dA8Z6tm5qdfPqeC2ybN9v+t3Cl/vYidb+uU91ovttw6flhp5oW3zCHe+SvIQDuWHEocvMgruq77nddTsgMIkbPodaTzT1qF+xChIVvna2+W/ns25vq+Oglu/F7lrjobrj64iPORXCVk82CyFRgoPUgtTklI02Zuxg3iGog6B8m9QHlMqObfhDPdvXoEMvxW9Gr/2nWN8kuIOpxcZxHOghdCTyIl/vUu//7a4kPaNDv07U3HJ1blF/Cg=
