#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker push jinwuzhao/emacs
docker tag jinwuzhao/emacs jinwuzhao/emacs:$TRAVIS_TAG
docker push jinwuzhao/emacs:$TRAVIS_TAG
docker logout
